// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go

// Package rest is a generated GoMock package.
package rest

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	api "github.com/s21platform/chat-service/internal/generated"
	model "github.com/s21platform/chat-service/internal/model"
)

// MockDBRepo is a mock of DBRepo interface.
type MockDBRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDBRepoMockRecorder
}

// MockDBRepoMockRecorder is the mock recorder for MockDBRepo.
type MockDBRepoMockRecorder struct {
	mock *MockDBRepo
}

// NewMockDBRepo creates a new mock instance.
func NewMockDBRepo(ctrl *gomock.Controller) *MockDBRepo {
	mock := &MockDBRepo{ctrl: ctrl}
	mock.recorder = &MockDBRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBRepo) EXPECT() *MockDBRepoMockRecorder {
	return m.recorder
}

// AddNewUser mocks base method.
func (m *MockDBRepo) AddNewUser(ctx context.Context, userInfo *model.StreamMemberParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddNewUser", ctx, userInfo)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddNewUser indicates an expected call of AddNewUser.
func (mr *MockDBRepoMockRecorder) AddNewUser(ctx, userInfo interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddNewUser", reflect.TypeOf((*MockDBRepo)(nil).AddNewUser), ctx, userInfo)
}

// AddStreamMembers mocks base method.
func (m *MockDBRepo) AddStreamMembers(ctx context.Context, streamID string, members []model.StreamMember) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddStreamMembers", ctx, streamID, members)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddStreamMembers indicates an expected call of AddStreamMembers.
func (mr *MockDBRepoMockRecorder) AddStreamMembers(ctx, streamID, members interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddStreamMembers", reflect.TypeOf((*MockDBRepo)(nil).AddStreamMembers), ctx, streamID, members)
}

// AddUserSubscriptions mocks base method.
func (m *MockDBRepo) AddUserSubscriptions(ctx context.Context, subscriptions []model.UserSubscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddUserSubscriptions", ctx, subscriptions)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddUserSubscriptions indicates an expected call of AddUserSubscriptions.
func (mr *MockDBRepoMockRecorder) AddUserSubscriptions(ctx, subscriptions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddUserSubscriptions", reflect.TypeOf((*MockDBRepo)(nil).AddUserSubscriptions), ctx, subscriptions)
}

// CreateStream mocks base method.
func (m *MockDBRepo) CreateStream(ctx context.Context, streamType, metadata, createdBy string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateStream", ctx, streamType, metadata, createdBy)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateStream indicates an expected call of CreateStream.
func (mr *MockDBRepoMockRecorder) CreateStream(ctx, streamType, metadata, createdBy interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateStream", reflect.TypeOf((*MockDBRepo)(nil).CreateStream), ctx, streamType, metadata, createdBy)
}

// GetPrivateStreams mocks base method.
func (m *MockDBRepo) GetPrivateStreams(ctx context.Context, requesterID string) (*model.PrivateStreamPreviewList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivateStreams", ctx, requesterID)
	ret0, _ := ret[0].(*model.PrivateStreamPreviewList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivateStreams indicates an expected call of GetPrivateStreams.
func (mr *MockDBRepoMockRecorder) GetPrivateStreams(ctx, requesterID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivateStreams", reflect.TypeOf((*MockDBRepo)(nil).GetPrivateStreams), ctx, requesterID)
}

// GetStreamRecentMessages mocks base method.
func (m *MockDBRepo) GetStreamRecentMessages(ctx context.Context, streamID, offset string, limit int32) (*model.MessageList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetStreamRecentMessages", ctx, streamID, offset, limit)
	ret0, _ := ret[0].(*model.MessageList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetStreamRecentMessages indicates an expected call of GetStreamRecentMessages.
func (mr *MockDBRepoMockRecorder) GetStreamRecentMessages(ctx, streamID, offset, limit interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetStreamRecentMessages", reflect.TypeOf((*MockDBRepo)(nil).GetStreamRecentMessages), ctx, streamID, offset, limit)
}

// GetUserActiveStreams mocks base method.
func (m *MockDBRepo) GetUserActiveStreams(ctx context.Context, userID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserActiveStreams", ctx, userID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserActiveStreams indicates an expected call of GetUserActiveStreams.
func (mr *MockDBRepoMockRecorder) GetUserActiveStreams(ctx, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserActiveStreams", reflect.TypeOf((*MockDBRepo)(nil).GetUserActiveStreams), ctx, userID)
}

// IsStreamMember mocks base method.
func (m *MockDBRepo) IsStreamMember(ctx context.Context, streamID, userID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsStreamMember", ctx, streamID, userID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsStreamMember indicates an expected call of IsStreamMember.
func (mr *MockDBRepoMockRecorder) IsStreamMember(ctx, streamID, userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsStreamMember", reflect.TypeOf((*MockDBRepo)(nil).IsStreamMember), ctx, streamID, userID)
}

// SaveMessage mocks base method.
func (m *MockDBRepo) SaveMessage(ctx context.Context, message *model.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SaveMessage", ctx, message)
	ret0, _ := ret[0].(error)
	return ret0
}

// SaveMessage indicates an expected call of SaveMessage.
func (mr *MockDBRepoMockRecorder) SaveMessage(ctx, message interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SaveMessage", reflect.TypeOf((*MockDBRepo)(nil).SaveMessage), ctx, message)
}

// WithTx mocks base method.
func (m *MockDBRepo) WithTx(ctx context.Context, cb func(context.Context) error) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", ctx, cb)
	ret0, _ := ret[0].(error)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockDBRepoMockRecorder) WithTx(ctx, cb interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockDBRepo)(nil).WithTx), ctx, cb)
}

// MockUserClient is a mock of UserClient interface.
type MockUserClient struct {
	ctrl     *gomock.Controller
	recorder *MockUserClientMockRecorder
}

// MockUserClientMockRecorder is the mock recorder for MockUserClient.
type MockUserClientMockRecorder struct {
	mock *MockUserClient
}

// NewMockUserClient creates a new mock instance.
func NewMockUserClient(ctrl *gomock.Controller) *MockUserClient {
	mock := &MockUserClient{ctrl: ctrl}
	mock.recorder = &MockUserClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserClient) EXPECT() *MockUserClientMockRecorder {
	return m.recorder
}

// GetUserInfoByUUID mocks base method.
func (m *MockUserClient) GetUserInfoByUUID(ctx context.Context, userUUID string) (*model.StreamMemberParams, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfoByUUID", ctx, userUUID)
	ret0, _ := ret[0].(*model.StreamMemberParams)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfoByUUID indicates an expected call of GetUserInfoByUUID.
func (mr *MockUserClientMockRecorder) GetUserInfoByUUID(ctx, userUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfoByUUID", reflect.TypeOf((*MockUserClient)(nil).GetUserInfoByUUID), ctx, userUUID)
}

// MockCetrifugeClient is a mock of CetrifugeClient interface.
type MockCetrifugeClient struct {
	ctrl     *gomock.Controller
	recorder *MockCetrifugeClientMockRecorder
}

// MockCetrifugeClientMockRecorder is the mock recorder for MockCetrifugeClient.
type MockCetrifugeClientMockRecorder struct {
	mock *MockCetrifugeClient
}

// NewMockCetrifugeClient creates a new mock instance.
func NewMockCetrifugeClient(ctrl *gomock.Controller) *MockCetrifugeClient {
	mock := &MockCetrifugeClient{ctrl: ctrl}
	mock.recorder = &MockCetrifugeClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCetrifugeClient) EXPECT() *MockCetrifugeClientMockRecorder {
	return m.recorder
}

// Publish mocks base method.
func (m *MockCetrifugeClient) Publish(ctx context.Context, channel string, data model.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, channel, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Publish indicates an expected call of Publish.
func (mr *MockCetrifugeClientMockRecorder) Publish(ctx, channel, data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockCetrifugeClient)(nil).Publish), ctx, channel, data)
}

// MockValidator is a mock of Validator interface.
type MockValidator struct {
	ctrl     *gomock.Controller
	recorder *MockValidatorMockRecorder
}

// MockValidatorMockRecorder is the mock recorder for MockValidator.
type MockValidatorMockRecorder struct {
	mock *MockValidator
}

// NewMockValidator creates a new mock instance.
func NewMockValidator(ctrl *gomock.Controller) *MockValidator {
	mock := &MockValidator{ctrl: ctrl}
	mock.recorder = &MockValidatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockValidator) EXPECT() *MockValidatorMockRecorder {
	return m.recorder
}

// ValidateCreateStream mocks base method.
func (m *MockValidator) ValidateCreateStream(req *api.CreateStreamRequest, creatorID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateCreateStream", req, creatorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateCreateStream indicates an expected call of ValidateCreateStream.
func (mr *MockValidatorMockRecorder) ValidateCreateStream(req, creatorID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateCreateStream", reflect.TypeOf((*MockValidator)(nil).ValidateCreateStream), req, creatorID)
}

// ValidateSendMessage mocks base method.
func (m *MockValidator) ValidateSendMessage(req *api.SendMessageRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSendMessage", req)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateSendMessage indicates an expected call of ValidateSendMessage.
func (mr *MockValidatorMockRecorder) ValidateSendMessage(req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSendMessage", reflect.TypeOf((*MockValidator)(nil).ValidateSendMessage), req)
}

// MockJWTGenerator is a mock of JWTGenerator interface.
type MockJWTGenerator struct {
	ctrl     *gomock.Controller
	recorder *MockJWTGeneratorMockRecorder
}

// MockJWTGeneratorMockRecorder is the mock recorder for MockJWTGenerator.
type MockJWTGeneratorMockRecorder struct {
	mock *MockJWTGenerator
}

// NewMockJWTGenerator creates a new mock instance.
func NewMockJWTGenerator(ctrl *gomock.Controller) *MockJWTGenerator {
	mock := &MockJWTGenerator{ctrl: ctrl}
	mock.recorder = &MockJWTGeneratorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockJWTGenerator) EXPECT() *MockJWTGeneratorMockRecorder {
	return m.recorder
}

// GenerateConnectToken mocks base method.
func (m *MockJWTGenerator) GenerateConnectToken(userID string) (string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateConnectToken", userID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateConnectToken indicates an expected call of GenerateConnectToken.
func (mr *MockJWTGeneratorMockRecorder) GenerateConnectToken(userID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateConnectToken", reflect.TypeOf((*MockJWTGenerator)(nil).GenerateConnectToken), userID)
}

// GenerateSubscribeToken mocks base method.
func (m *MockJWTGenerator) GenerateSubscribeToken(userID, streamID string) (string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateSubscribeToken", userID, streamID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateSubscribeToken indicates an expected call of GenerateSubscribeToken.
func (mr *MockJWTGeneratorMockRecorder) GenerateSubscribeToken(userID, streamID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateSubscribeToken", reflect.TypeOf((*MockJWTGenerator)(nil).GenerateSubscribeToken), userID, streamID)
}

// ValidateConnectToken mocks base method.
func (m *MockJWTGenerator) ValidateConnectToken(tokenString string) (*model.CentrifugoConnectClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateConnectToken", tokenString)
	ret0, _ := ret[0].(*model.CentrifugoConnectClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateConnectToken indicates an expected call of ValidateConnectToken.
func (mr *MockJWTGeneratorMockRecorder) ValidateConnectToken(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateConnectToken", reflect.TypeOf((*MockJWTGenerator)(nil).ValidateConnectToken), tokenString)
}

// ValidateSubscribeToken mocks base method.
func (m *MockJWTGenerator) ValidateSubscribeToken(tokenString string) (*model.CentrifugoSubscribeClaims, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateSubscribeToken", tokenString)
	ret0, _ := ret[0].(*model.CentrifugoSubscribeClaims)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ValidateSubscribeToken indicates an expected call of ValidateSubscribeToken.
func (mr *MockJWTGeneratorMockRecorder) ValidateSubscribeToken(tokenString interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateSubscribeToken", reflect.TypeOf((*MockJWTGenerator)(nil).ValidateSubscribeToken), tokenString)
}
