// Code generated by MockGen. DO NOT EDIT.
// Source: contract.go

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	model "github.com/s21platform/chat-service/internal/model"
)

// MockDBRepo is a mock of DBRepo interface.
type MockDBRepo struct {
	ctrl     *gomock.Controller
	recorder *MockDBRepoMockRecorder
}

// MockDBRepoMockRecorder is the mock recorder for MockDBRepo.
type MockDBRepoMockRecorder struct {
	mock *MockDBRepo
}

// NewMockDBRepo creates a new mock instance.
func NewMockDBRepo(ctrl *gomock.Controller) *MockDBRepo {
	mock := &MockDBRepo{ctrl: ctrl}
	mock.recorder = &MockDBRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDBRepo) EXPECT() *MockDBRepoMockRecorder {
	return m.recorder
}

// AddPrivateChatMember mocks base method.
func (m *MockDBRepo) AddPrivateChatMember(ctx context.Context, chatUUID string, member *model.ChatMemberParams) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPrivateChatMember", ctx, chatUUID, member)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddPrivateChatMember indicates an expected call of AddPrivateChatMember.
func (mr *MockDBRepoMockRecorder) AddPrivateChatMember(ctx, chatUUID, member interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPrivateChatMember", reflect.TypeOf((*MockDBRepo)(nil).AddPrivateChatMember), ctx, chatUUID, member)
}

// CreatePrivateChat mocks base method.
func (m *MockDBRepo) CreatePrivateChat(ctx context.Context) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePrivateChat", ctx)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePrivateChat indicates an expected call of CreatePrivateChat.
func (mr *MockDBRepoMockRecorder) CreatePrivateChat(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePrivateChat", reflect.TypeOf((*MockDBRepo)(nil).CreatePrivateChat), ctx)
}

// DeletePrivateMessage mocks base method.
func (m *MockDBRepo) DeletePrivateMessage(ctx context.Context, userUUID, messageID, mode string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePrivateMessage", ctx, userUUID, messageID, mode)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeletePrivateMessage indicates an expected call of DeletePrivateMessage.
func (mr *MockDBRepoMockRecorder) DeletePrivateMessage(ctx, userUUID, messageID, mode interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePrivateMessage", reflect.TypeOf((*MockDBRepo)(nil).DeletePrivateMessage), ctx, userUUID, messageID, mode)
}

// EditPrivateMessage mocks base method.
func (m *MockDBRepo) EditPrivateMessage(ctx context.Context, messageUUID, newContent string) (*model.EditedMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "EditPrivateMessage", ctx, messageUUID, newContent)
	ret0, _ := ret[0].(*model.EditedMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// EditPrivateMessage indicates an expected call of EditPrivateMessage.
func (mr *MockDBRepoMockRecorder) EditPrivateMessage(ctx, messageUUID, newContent interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "EditPrivateMessage", reflect.TypeOf((*MockDBRepo)(nil).EditPrivateMessage), ctx, messageUUID, newContent)
}

// GetGroupChats mocks base method.
func (m *MockDBRepo) GetGroupChats(ctx context.Context, userUUID string) (*model.ChatInfoList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGroupChats", ctx, userUUID)
	ret0, _ := ret[0].(*model.ChatInfoList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGroupChats indicates an expected call of GetGroupChats.
func (mr *MockDBRepoMockRecorder) GetGroupChats(ctx, userUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGroupChats", reflect.TypeOf((*MockDBRepo)(nil).GetGroupChats), ctx, userUUID)
}

// GetPrivateChats mocks base method.
func (m *MockDBRepo) GetPrivateChats(ctx context.Context, userUUID string) (*model.ChatInfoList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivateChats", ctx, userUUID)
	ret0, _ := ret[0].(*model.ChatInfoList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivateChats indicates an expected call of GetPrivateChats.
func (mr *MockDBRepoMockRecorder) GetPrivateChats(ctx, userUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivateChats", reflect.TypeOf((*MockDBRepo)(nil).GetPrivateChats), ctx, userUUID)
}

// GetPrivateDeletionInfo mocks base method.
func (m *MockDBRepo) GetPrivateDeletionInfo(ctx context.Context, messageID string) (*model.DeletionInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivateDeletionInfo", ctx, messageID)
	ret0, _ := ret[0].(*model.DeletionInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivateDeletionInfo indicates an expected call of GetPrivateDeletionInfo.
func (mr *MockDBRepoMockRecorder) GetPrivateDeletionInfo(ctx, messageID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivateDeletionInfo", reflect.TypeOf((*MockDBRepo)(nil).GetPrivateDeletionInfo), ctx, messageID)
}

// GetPrivateRecentMessages mocks base method.
func (m *MockDBRepo) GetPrivateRecentMessages(ctx context.Context, chatUUID, userUUID string) (*model.MessageList, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPrivateRecentMessages", ctx, chatUUID, userUUID)
	ret0, _ := ret[0].(*model.MessageList)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPrivateRecentMessages indicates an expected call of GetPrivateRecentMessages.
func (mr *MockDBRepoMockRecorder) GetPrivateRecentMessages(ctx, chatUUID, userUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPrivateRecentMessages", reflect.TypeOf((*MockDBRepo)(nil).GetPrivateRecentMessages), ctx, chatUUID, userUUID)
}

// IsChatMember mocks base method.
func (m *MockDBRepo) IsChatMember(ctx context.Context, chatUUID, userUUID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsChatMember", ctx, chatUUID, userUUID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsChatMember indicates an expected call of IsChatMember.
func (mr *MockDBRepoMockRecorder) IsChatMember(ctx, chatUUID, userUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsChatMember", reflect.TypeOf((*MockDBRepo)(nil).IsChatMember), ctx, chatUUID, userUUID)
}

// IsMessageOwner mocks base method.
func (m *MockDBRepo) IsMessageOwner(ctx context.Context, chatUUID, messageUUID, userUUID string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsMessageOwner", ctx, chatUUID, messageUUID, userUUID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsMessageOwner indicates an expected call of IsMessageOwner.
func (mr *MockDBRepoMockRecorder) IsMessageOwner(ctx, chatUUID, messageUUID, userUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsMessageOwner", reflect.TypeOf((*MockDBRepo)(nil).IsMessageOwner), ctx, chatUUID, messageUUID, userUUID)
}

// MockUserClient is a mock of UserClient interface.
type MockUserClient struct {
	ctrl     *gomock.Controller
	recorder *MockUserClientMockRecorder
}

// MockUserClientMockRecorder is the mock recorder for MockUserClient.
type MockUserClientMockRecorder struct {
	mock *MockUserClient
}

// NewMockUserClient creates a new mock instance.
func NewMockUserClient(ctrl *gomock.Controller) *MockUserClient {
	mock := &MockUserClient{ctrl: ctrl}
	mock.recorder = &MockUserClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserClient) EXPECT() *MockUserClientMockRecorder {
	return m.recorder
}

// GetUserInfoByUUID mocks base method.
func (m *MockUserClient) GetUserInfoByUUID(ctx context.Context, userUUID string) (*model.ChatMemberParams, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfoByUUID", ctx, userUUID)
	ret0, _ := ret[0].(*model.ChatMemberParams)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfoByUUID indicates an expected call of GetUserInfoByUUID.
func (mr *MockUserClientMockRecorder) GetUserInfoByUUID(ctx, userUUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfoByUUID", reflect.TypeOf((*MockUserClient)(nil).GetUserInfoByUUID), ctx, userUUID)
}
