// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: api/chat.proto

package chat

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ChatUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`             // id пользователя
	Metadata      string                 `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"` // метаданные пользователя
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatUser) Reset() {
	*x = ChatUser{}
	mi := &file_api_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatUser) ProtoMessage() {}

func (x *ChatUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatUser.ProtoReflect.Descriptor instead.
func (*ChatUser) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ChatUser) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ChatUser) GetMetadata() string {
	if x != nil {
		return x.Metadata
	}
	return ""
}

type CreateStreamIn struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Users           []*ChatUser            `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`                                            // пользователи стрима
	Type            string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`                                              // тип стрима
	ChatMetadata    string                 `protobuf:"bytes,3,opt,name=chat_metadata,json=chatMetadata,proto3" json:"chat_metadata,omitempty"`          // метаданные чата
	CreatorMetadata string                 `protobuf:"bytes,4,opt,name=creator_metadata,json=creatorMetadata,proto3" json:"creator_metadata,omitempty"` // метаданные создателя
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateStreamIn) Reset() {
	*x = CreateStreamIn{}
	mi := &file_api_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStreamIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStreamIn) ProtoMessage() {}

func (x *CreateStreamIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStreamIn.ProtoReflect.Descriptor instead.
func (*CreateStreamIn) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{1}
}

func (x *CreateStreamIn) GetUsers() []*ChatUser {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *CreateStreamIn) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *CreateStreamIn) GetChatMetadata() string {
	if x != nil {
		return x.ChatMetadata
	}
	return ""
}

func (x *CreateStreamIn) GetCreatorMetadata() string {
	if x != nil {
		return x.CreatorMetadata
	}
	return ""
}

type CreateStreamOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"` // id созданного стрима
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateStreamOut) Reset() {
	*x = CreateStreamOut{}
	mi := &file_api_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateStreamOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateStreamOut) ProtoMessage() {}

func (x *CreateStreamOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateStreamOut.ProtoReflect.Descriptor instead.
func (*CreateStreamOut) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{2}
}

func (x *CreateStreamOut) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type PrivateStream struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	StreamId             string                 `protobuf:"bytes,5,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`                                       // ID стрима
	LastMessageContent   string                 `protobuf:"bytes,1,opt,name=last_message_content,json=lastMessageContent,proto3" json:"last_message_content,omitempty"`       // Контент последнего сообщения
	StreamName           string                 `protobuf:"bytes,2,opt,name=stream_name,json=streamName,proto3" json:"stream_name,omitempty"`                                 // Название стрима
	AvatarUrl            string                 `protobuf:"bytes,3,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`                                    // Аватарка стрима
	LastMessageTimestamp string                 `protobuf:"bytes,4,opt,name=last_message_timestamp,json=lastMessageTimestamp,proto3" json:"last_message_timestamp,omitempty"` // Время отправки последнего сообщения
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *PrivateStream) Reset() {
	*x = PrivateStream{}
	mi := &file_api_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PrivateStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PrivateStream) ProtoMessage() {}

func (x *PrivateStream) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PrivateStream.ProtoReflect.Descriptor instead.
func (*PrivateStream) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{3}
}

func (x *PrivateStream) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *PrivateStream) GetLastMessageContent() string {
	if x != nil {
		return x.LastMessageContent
	}
	return ""
}

func (x *PrivateStream) GetStreamName() string {
	if x != nil {
		return x.StreamName
	}
	return ""
}

func (x *PrivateStream) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *PrivateStream) GetLastMessageTimestamp() string {
	if x != nil {
		return x.LastMessageTimestamp
	}
	return ""
}

type GetPrivateStreamsOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Streams       []*PrivateStream       `protobuf:"bytes,1,rep,name=streams,proto3" json:"streams,omitempty"` // Список стримов
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPrivateStreamsOut) Reset() {
	*x = GetPrivateStreamsOut{}
	mi := &file_api_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPrivateStreamsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPrivateStreamsOut) ProtoMessage() {}

func (x *GetPrivateStreamsOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPrivateStreamsOut.ProtoReflect.Descriptor instead.
func (*GetPrivateStreamsOut) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{4}
}

func (x *GetPrivateStreamsOut) GetStreams() []*PrivateStream {
	if x != nil {
		return x.Streams
	}
	return nil
}

type Message struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Uuid          string                 `protobuf:"bytes,1,opt,name=uuid,proto3" json:"uuid,omitempty"`                               // uuid пользователя
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                         // само сообщение
	SentAt        string                 `protobuf:"bytes,3,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`             // время отправки
	UpdatedAt     string                 `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`    // время обновления
	RootUuid      string                 `protobuf:"bytes,5,opt,name=root_uuid,json=rootUuid,proto3" json:"root_uuid,omitempty"`       // uuid корневого сообщения
	ParentUuid    string                 `protobuf:"bytes,6,opt,name=parent_uuid,json=parentUuid,proto3" json:"parent_uuid,omitempty"` // uuid сообщения, на которое идет прямой ответ
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_api_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{5}
}

func (x *Message) GetUuid() string {
	if x != nil {
		return x.Uuid
	}
	return ""
}

func (x *Message) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Message) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

func (x *Message) GetUpdatedAt() string {
	if x != nil {
		return x.UpdatedAt
	}
	return ""
}

func (x *Message) GetRootUuid() string {
	if x != nil {
		return x.RootUuid
	}
	return ""
}

func (x *Message) GetParentUuid() string {
	if x != nil {
		return x.ParentUuid
	}
	return ""
}

type GetStreamRecentMessagesIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"` // ID стрима, из которого достаем сообщения
	Offset        string                 `protobuf:"bytes,2,opt,name=offset,proto3" json:"offset,omitempty"`                     // временная метка для offset (RFC3339)
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`                      // количество сообщений для возврата
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamRecentMessagesIn) Reset() {
	*x = GetStreamRecentMessagesIn{}
	mi := &file_api_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamRecentMessagesIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamRecentMessagesIn) ProtoMessage() {}

func (x *GetStreamRecentMessagesIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamRecentMessagesIn.ProtoReflect.Descriptor instead.
func (*GetStreamRecentMessagesIn) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{6}
}

func (x *GetStreamRecentMessagesIn) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *GetStreamRecentMessagesIn) GetOffset() string {
	if x != nil {
		return x.Offset
	}
	return ""
}

func (x *GetStreamRecentMessagesIn) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetStreamRecentMessagesOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*Message             `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"` // список сообщений
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamRecentMessagesOut) Reset() {
	*x = GetStreamRecentMessagesOut{}
	mi := &file_api_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamRecentMessagesOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamRecentMessagesOut) ProtoMessage() {}

func (x *GetStreamRecentMessagesOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamRecentMessagesOut.ProtoReflect.Descriptor instead.
func (*GetStreamRecentMessagesOut) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{7}
}

func (x *GetStreamRecentMessagesOut) GetMessages() []*Message {
	if x != nil {
		return x.Messages
	}
	return nil
}

type SendMessageIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`          // ID стрима
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`                            // текст сообщения
	ParentId      *string                `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3,oneof" json:"parent_id,omitempty"`    // ID сообщения для reply (опционально)
	RootId        *string                `protobuf:"bytes,4,opt,name=root_id,json=rootId,proto3,oneof" json:"root_id,omitempty"`          // ID корневого сообщения треда (опционально)
	MessageType   string                 `protobuf:"bytes,5,opt,name=message_type,json=messageType,proto3" json:"message_type,omitempty"` // тип сообщения (text, image, file)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageIn) Reset() {
	*x = SendMessageIn{}
	mi := &file_api_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageIn) ProtoMessage() {}

func (x *SendMessageIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageIn.ProtoReflect.Descriptor instead.
func (*SendMessageIn) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{8}
}

func (x *SendMessageIn) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *SendMessageIn) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendMessageIn) GetParentId() string {
	if x != nil && x.ParentId != nil {
		return *x.ParentId
	}
	return ""
}

func (x *SendMessageIn) GetRootId() string {
	if x != nil && x.RootId != nil {
		return *x.RootId
	}
	return ""
}

func (x *SendMessageIn) GetMessageType() string {
	if x != nil {
		return x.MessageType
	}
	return ""
}

type SendMessageOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"` // ID созданного сообщения
	SentAt        string                 `protobuf:"bytes,2,opt,name=sent_at,json=sentAt,proto3" json:"sent_at,omitempty"`          // время отправки
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageOut) Reset() {
	*x = SendMessageOut{}
	mi := &file_api_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageOut) ProtoMessage() {}

func (x *SendMessageOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageOut.ProtoReflect.Descriptor instead.
func (*SendMessageOut) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{9}
}

func (x *SendMessageOut) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *SendMessageOut) GetSentAt() string {
	if x != nil {
		return x.SentAt
	}
	return ""
}

type GetConnectAccessTokenOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                           // JWT токен для подключения к Centrifugo
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // время истечения токена (unix timestamp)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetConnectAccessTokenOut) Reset() {
	*x = GetConnectAccessTokenOut{}
	mi := &file_api_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectAccessTokenOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectAccessTokenOut) ProtoMessage() {}

func (x *GetConnectAccessTokenOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectAccessTokenOut.ProtoReflect.Descriptor instead.
func (*GetConnectAccessTokenOut) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{10}
}

func (x *GetConnectAccessTokenOut) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetConnectAccessTokenOut) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

type GetStreamSubscribeTokenIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"` // ID стрима для получения subscribe токена
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamSubscribeTokenIn) Reset() {
	*x = GetStreamSubscribeTokenIn{}
	mi := &file_api_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamSubscribeTokenIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamSubscribeTokenIn) ProtoMessage() {}

func (x *GetStreamSubscribeTokenIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamSubscribeTokenIn.ProtoReflect.Descriptor instead.
func (*GetStreamSubscribeTokenIn) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{11}
}

func (x *GetStreamSubscribeTokenIn) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

type GetStreamSubscribeTokenOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`                           // JWT токен для подписки на канал стрима
	ExpiresAt     int64                  `protobuf:"varint,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // время истечения токена (unix timestamp)
	Channel       string                 `protobuf:"bytes,3,opt,name=channel,proto3" json:"channel,omitempty"`                       // канал для подписки в Centrifugo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStreamSubscribeTokenOut) Reset() {
	*x = GetStreamSubscribeTokenOut{}
	mi := &file_api_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStreamSubscribeTokenOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStreamSubscribeTokenOut) ProtoMessage() {}

func (x *GetStreamSubscribeTokenOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStreamSubscribeTokenOut.ProtoReflect.Descriptor instead.
func (*GetStreamSubscribeTokenOut) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{12}
}

func (x *GetStreamSubscribeTokenOut) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetStreamSubscribeTokenOut) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *GetStreamSubscribeTokenOut) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type GetUserActiveStreamsOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamIds     []string               `protobuf:"bytes,1,rep,name=stream_ids,json=streamIds,proto3" json:"stream_ids,omitempty"` // Список ID стримов где пользователь является участником
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserActiveStreamsOut) Reset() {
	*x = GetUserActiveStreamsOut{}
	mi := &file_api_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserActiveStreamsOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserActiveStreamsOut) ProtoMessage() {}

func (x *GetUserActiveStreamsOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserActiveStreamsOut.ProtoReflect.Descriptor instead.
func (*GetUserActiveStreamsOut) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{13}
}

func (x *GetUserActiveStreamsOut) GetStreamIds() []string {
	if x != nil {
		return x.StreamIds
	}
	return nil
}

type StreamSubscription struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamId      string                 `protobuf:"bytes,1,opt,name=stream_id,json=streamId,proto3" json:"stream_id,omitempty"`     // ID стрима
	Token         string                 `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`                           // JWT токен для подписки
	ExpiresAt     int64                  `protobuf:"varint,3,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"` // время истечения токена
	Channel       string                 `protobuf:"bytes,4,opt,name=channel,proto3" json:"channel,omitempty"`                       // канал для подписки в Centrifugo
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamSubscription) Reset() {
	*x = StreamSubscription{}
	mi := &file_api_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamSubscription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamSubscription) ProtoMessage() {}

func (x *StreamSubscription) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamSubscription.ProtoReflect.Descriptor instead.
func (*StreamSubscription) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{14}
}

func (x *StreamSubscription) GetStreamId() string {
	if x != nil {
		return x.StreamId
	}
	return ""
}

func (x *StreamSubscription) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *StreamSubscription) GetExpiresAt() int64 {
	if x != nil {
		return x.ExpiresAt
	}
	return 0
}

func (x *StreamSubscription) GetChannel() string {
	if x != nil {
		return x.Channel
	}
	return ""
}

type GetBatchSubscribeTokensIn struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	StreamIds     []string               `protobuf:"bytes,1,rep,name=stream_ids,json=streamIds,proto3" json:"stream_ids,omitempty"` // Список ID стримов для которых нужны токены
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchSubscribeTokensIn) Reset() {
	*x = GetBatchSubscribeTokensIn{}
	mi := &file_api_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchSubscribeTokensIn) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchSubscribeTokensIn) ProtoMessage() {}

func (x *GetBatchSubscribeTokensIn) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchSubscribeTokensIn.ProtoReflect.Descriptor instead.
func (*GetBatchSubscribeTokensIn) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{15}
}

func (x *GetBatchSubscribeTokensIn) GetStreamIds() []string {
	if x != nil {
		return x.StreamIds
	}
	return nil
}

type GetBatchSubscribeTokensOut struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subscriptions []*StreamSubscription  `protobuf:"bytes,1,rep,name=subscriptions,proto3" json:"subscriptions,omitempty"` // Токены для подписки на стримы
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBatchSubscribeTokensOut) Reset() {
	*x = GetBatchSubscribeTokensOut{}
	mi := &file_api_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBatchSubscribeTokensOut) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBatchSubscribeTokensOut) ProtoMessage() {}

func (x *GetBatchSubscribeTokensOut) ProtoReflect() protoreflect.Message {
	mi := &file_api_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBatchSubscribeTokensOut.ProtoReflect.Descriptor instead.
func (*GetBatchSubscribeTokensOut) Descriptor() ([]byte, []int) {
	return file_api_chat_proto_rawDescGZIP(), []int{16}
}

func (x *GetBatchSubscribeTokensOut) GetSubscriptions() []*StreamSubscription {
	if x != nil {
		return x.Subscriptions
	}
	return nil
}

var File_api_chat_proto protoreflect.FileDescriptor

const file_api_chat_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/chat.proto\x1a\x1bgoogle/protobuf/empty.proto\"6\n" +
	"\bChatUser\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1a\n" +
	"\bmetadata\x18\x02 \x01(\tR\bmetadata\"\x95\x01\n" +
	"\x0eCreateStreamIn\x12\x1f\n" +
	"\x05users\x18\x01 \x03(\v2\t.ChatUserR\x05users\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12#\n" +
	"\rchat_metadata\x18\x03 \x01(\tR\fchatMetadata\x12)\n" +
	"\x10creator_metadata\x18\x04 \x01(\tR\x0fcreatorMetadata\"!\n" +
	"\x0fCreateStreamOut\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xd4\x01\n" +
	"\rPrivateStream\x12\x1b\n" +
	"\tstream_id\x18\x05 \x01(\tR\bstreamId\x120\n" +
	"\x14last_message_content\x18\x01 \x01(\tR\x12lastMessageContent\x12\x1f\n" +
	"\vstream_name\x18\x02 \x01(\tR\n" +
	"streamName\x12\x1d\n" +
	"\n" +
	"avatar_url\x18\x03 \x01(\tR\tavatarUrl\x124\n" +
	"\x16last_message_timestamp\x18\x04 \x01(\tR\x14lastMessageTimestamp\"@\n" +
	"\x14GetPrivateStreamsOut\x12(\n" +
	"\astreams\x18\x01 \x03(\v2\x0e.PrivateStreamR\astreams\"\xad\x01\n" +
	"\aMessage\x12\x12\n" +
	"\x04uuid\x18\x01 \x01(\tR\x04uuid\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12\x17\n" +
	"\asent_at\x18\x03 \x01(\tR\x06sentAt\x12\x1d\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\tR\tupdatedAt\x12\x1b\n" +
	"\troot_uuid\x18\x05 \x01(\tR\brootUuid\x12\x1f\n" +
	"\vparent_uuid\x18\x06 \x01(\tR\n" +
	"parentUuid\"f\n" +
	"\x19GetStreamRecentMessagesIn\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\tR\x06offset\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\"B\n" +
	"\x1aGetStreamRecentMessagesOut\x12$\n" +
	"\bmessages\x18\x01 \x03(\v2\b.MessageR\bmessages\"\xc3\x01\n" +
	"\rSendMessageIn\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x18\n" +
	"\acontent\x18\x02 \x01(\tR\acontent\x12 \n" +
	"\tparent_id\x18\x03 \x01(\tH\x00R\bparentId\x88\x01\x01\x12\x1c\n" +
	"\aroot_id\x18\x04 \x01(\tH\x01R\x06rootId\x88\x01\x01\x12!\n" +
	"\fmessage_type\x18\x05 \x01(\tR\vmessageTypeB\f\n" +
	"\n" +
	"_parent_idB\n" +
	"\n" +
	"\b_root_id\"H\n" +
	"\x0eSendMessageOut\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x17\n" +
	"\asent_at\x18\x02 \x01(\tR\x06sentAt\"O\n" +
	"\x18GetConnectAccessTokenOut\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\"8\n" +
	"\x19GetStreamSubscribeTokenIn\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\"k\n" +
	"\x1aGetStreamSubscribeTokenOut\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\x03R\texpiresAt\x12\x18\n" +
	"\achannel\x18\x03 \x01(\tR\achannel\"8\n" +
	"\x17GetUserActiveStreamsOut\x12\x1d\n" +
	"\n" +
	"stream_ids\x18\x01 \x03(\tR\tstreamIds\"\x80\x01\n" +
	"\x12StreamSubscription\x12\x1b\n" +
	"\tstream_id\x18\x01 \x01(\tR\bstreamId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"expires_at\x18\x03 \x01(\x03R\texpiresAt\x12\x18\n" +
	"\achannel\x18\x04 \x01(\tR\achannel\":\n" +
	"\x19GetBatchSubscribeTokensIn\x12\x1d\n" +
	"\n" +
	"stream_ids\x18\x01 \x03(\tR\tstreamIds\"W\n" +
	"\x1aGetBatchSubscribeTokensOut\x129\n" +
	"\rsubscriptions\x18\x01 \x03(\v2\x13.StreamSubscriptionR\rsubscriptions2\xd6\x04\n" +
	"\vChatService\x123\n" +
	"\fCreateStream\x12\x0f.CreateStreamIn\x1a\x10.CreateStreamOut\"\x00\x120\n" +
	"\vSendMessage\x12\x0e.SendMessageIn\x1a\x0f.SendMessageOut\"\x00\x12D\n" +
	"\x11GetPrivateStreams\x12\x16.google.protobuf.Empty\x1a\x15.GetPrivateStreamsOut\"\x00\x12T\n" +
	"\x17GetStreamRecentMessages\x12\x1a.GetStreamRecentMessagesIn\x1a\x1b.GetStreamRecentMessagesOut\"\x00\x12L\n" +
	"\x15GetConnectAccessToken\x12\x16.google.protobuf.Empty\x1a\x19.GetConnectAccessTokenOut\"\x00\x12T\n" +
	"\x17GetStreamSubscribeToken\x12\x1a.GetStreamSubscribeTokenIn\x1a\x1b.GetStreamSubscribeTokenOut\"\x00\x12J\n" +
	"\x14GetUserActiveStreams\x12\x16.google.protobuf.Empty\x1a\x18.GetUserActiveStreamsOut\"\x00\x12T\n" +
	"\x17GetBatchSubscribeTokens\x12\x1a.GetBatchSubscribeTokensIn\x1a\x1b.GetBatchSubscribeTokensOut\"\x00B\n" +
	"Z\bpkg/chatb\x06proto3"

var (
	file_api_chat_proto_rawDescOnce sync.Once
	file_api_chat_proto_rawDescData []byte
)

func file_api_chat_proto_rawDescGZIP() []byte {
	file_api_chat_proto_rawDescOnce.Do(func() {
		file_api_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_chat_proto_rawDesc), len(file_api_chat_proto_rawDesc)))
	})
	return file_api_chat_proto_rawDescData
}

var file_api_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_chat_proto_goTypes = []any{
	(*ChatUser)(nil),                   // 0: ChatUser
	(*CreateStreamIn)(nil),             // 1: CreateStreamIn
	(*CreateStreamOut)(nil),            // 2: CreateStreamOut
	(*PrivateStream)(nil),              // 3: PrivateStream
	(*GetPrivateStreamsOut)(nil),       // 4: GetPrivateStreamsOut
	(*Message)(nil),                    // 5: Message
	(*GetStreamRecentMessagesIn)(nil),  // 6: GetStreamRecentMessagesIn
	(*GetStreamRecentMessagesOut)(nil), // 7: GetStreamRecentMessagesOut
	(*SendMessageIn)(nil),              // 8: SendMessageIn
	(*SendMessageOut)(nil),             // 9: SendMessageOut
	(*GetConnectAccessTokenOut)(nil),   // 10: GetConnectAccessTokenOut
	(*GetStreamSubscribeTokenIn)(nil),  // 11: GetStreamSubscribeTokenIn
	(*GetStreamSubscribeTokenOut)(nil), // 12: GetStreamSubscribeTokenOut
	(*GetUserActiveStreamsOut)(nil),    // 13: GetUserActiveStreamsOut
	(*StreamSubscription)(nil),         // 14: StreamSubscription
	(*GetBatchSubscribeTokensIn)(nil),  // 15: GetBatchSubscribeTokensIn
	(*GetBatchSubscribeTokensOut)(nil), // 16: GetBatchSubscribeTokensOut
	(*emptypb.Empty)(nil),              // 17: google.protobuf.Empty
}
var file_api_chat_proto_depIdxs = []int32{
	0,  // 0: CreateStreamIn.users:type_name -> ChatUser
	3,  // 1: GetPrivateStreamsOut.streams:type_name -> PrivateStream
	5,  // 2: GetStreamRecentMessagesOut.messages:type_name -> Message
	14, // 3: GetBatchSubscribeTokensOut.subscriptions:type_name -> StreamSubscription
	1,  // 4: ChatService.CreateStream:input_type -> CreateStreamIn
	8,  // 5: ChatService.SendMessage:input_type -> SendMessageIn
	17, // 6: ChatService.GetPrivateStreams:input_type -> google.protobuf.Empty
	6,  // 7: ChatService.GetStreamRecentMessages:input_type -> GetStreamRecentMessagesIn
	17, // 8: ChatService.GetConnectAccessToken:input_type -> google.protobuf.Empty
	11, // 9: ChatService.GetStreamSubscribeToken:input_type -> GetStreamSubscribeTokenIn
	17, // 10: ChatService.GetUserActiveStreams:input_type -> google.protobuf.Empty
	15, // 11: ChatService.GetBatchSubscribeTokens:input_type -> GetBatchSubscribeTokensIn
	2,  // 12: ChatService.CreateStream:output_type -> CreateStreamOut
	9,  // 13: ChatService.SendMessage:output_type -> SendMessageOut
	4,  // 14: ChatService.GetPrivateStreams:output_type -> GetPrivateStreamsOut
	7,  // 15: ChatService.GetStreamRecentMessages:output_type -> GetStreamRecentMessagesOut
	10, // 16: ChatService.GetConnectAccessToken:output_type -> GetConnectAccessTokenOut
	12, // 17: ChatService.GetStreamSubscribeToken:output_type -> GetStreamSubscribeTokenOut
	13, // 18: ChatService.GetUserActiveStreams:output_type -> GetUserActiveStreamsOut
	16, // 19: ChatService.GetBatchSubscribeTokens:output_type -> GetBatchSubscribeTokensOut
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_chat_proto_init() }
func file_api_chat_proto_init() {
	if File_api_chat_proto != nil {
		return
	}
	file_api_chat_proto_msgTypes[8].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_chat_proto_rawDesc), len(file_api_chat_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_chat_proto_goTypes,
		DependencyIndexes: file_api_chat_proto_depIdxs,
		MessageInfos:      file_api_chat_proto_msgTypes,
	}.Build()
	File_api_chat_proto = out.File
	file_api_chat_proto_goTypes = nil
	file_api_chat_proto_depIdxs = nil
}
